#############################################################
# https://github.com/pre-commit/pre-commit
#############################################################
# usage: pre-commit [-h] [-V] {autoupdate,clean,gc,init-templatedir,install,install-hooks,migrate-config,run,sample-config,try-repo,uninstall,validate-config,validate-manifest,help,hook-impl} ...
#
# positional arguments:
#   {autoupdate,clean,gc,init-templatedir,install,install-hooks,migrate-config,run,sample-config,try-repo,uninstall,validate-config,validate-manifest,help,hook-impl}
#     autoupdate          Auto-update pre-commit config to the latest repos' versions.
#     clean               Clean out pre-commit files.
#     gc                  Clean unused cached repos.
#     init-templatedir    Install hook script in a directory intended for use with `git config init.templateDir`.
#     install             Install the pre-commit script.
#     install-hooks       Install hook environments for all environments in the config file. You may find `pre-commit install --install-hooks` more useful.
#     migrate-config      Migrate list configuration to new map configuration.
#     run                 Run hooks.
#     sample-config       Produce a sample .pre-commit-config.yaml file
#     try-repo            Try the hooks in a repository, useful for developing new hooks.
#     uninstall           Uninstall the pre-commit script.
#     validate-config     Validate .pre-commit-config.yaml files
#     validate-manifest   Validate .pre-commit-hooks.yaml files
#     help                Show help for a specific command.
#############################################################
#
# Run locally:
#     pre-commit run -a
#
# Install (runs every time you commit in git):
#     pre-commit install
#
# Update revs in this file:
#     pre-commit autoupdate
#

default_stages: [pre-commit, pre-push]

repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
        args:
          - --allow-multiple-documents
          - --unsafe
        exclude: (^chart/|^ci\/chart\/\w+)
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args:
          - --fix=auto
            #- id: trailing-whitespace
      - id: check-json
      - id: pretty-format-json
        args:
          - --autofix
          - --no-ensure-ascii
          - --no-sort-keys
      - id: check-merge-conflict
      - id: destroyed-symlinks
      - id: check-symlinks
      - id: check-shebang-scripts-are-executable

  - repo: https://github.com/tcort/markdown-link-check
    rev: v3.12.1
    hooks:
      - id: markdown-link-check
        args: [-q]

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck
        args:
          - --check-sourced
          - --severity=error
          - --external-sources
