# shellcheck disable=SC2148,SC2149
######################################################################
# -- DO NOT EDIT THIS FILE --
# Add your customizations in ~/.zshrc_custom and they will
# be loaded automatically when you start a new shell session.
######################################################################

# load zsh profiler
# zmodload zsh/zprof

# get zsh load time - START
# prefer gnu-date
[[ "$(uname)" == "Darwin" ]] && (type gdate &>/dev/null) && alias date='gdate'
_zsh_start="$(date +%s%3N)"

# Export core paths before plugins: zsh-autocomplete runs compinit during plugin load.
export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_DATA_HOME="${HOME}/.local/share"

FPATH_DIRS=(
  "${HOME}/.completions"
  "${HOME}/.docker/completions"
  "${HOME}/.zsh/zsh-completions/src"
)
for i in "${FPATH_DIRS[@]}"; do
  [ -d "${i}" ] && FPATH+=":${i}"
done
(type brew &>/dev/null) && [ -n "${HOMEBREW_PREFIX:-}" ] && FPATH+=":${HOMEBREW_PREFIX}/share/zsh/site-functions"
export FPATH="${FPATH}"
unset FPATH_DIRS

# load zsh plugins (skip list: plugins that conflict with zsh-autocomplete)
typeset -a ZSH_PLUGINS_SKIP=(zsh-completions)
# ZSH_PLUGINS_SKIP+=(zsh-autosuggestions) # skips  waiting for https://github.com/marlonrichert/zsh-autocomplete/pull/8560
for plugin in $(\ls -1 ${HOME}/.zsh/ | sort | xargs); do
  ((${ZSH_PLUGINS_SKIP[(Ie)${plugin}]})) && continue
  plugin_dir="${HOME}/.zsh/${plugin}"
  plugin_file="$(find "${plugin_dir}" -maxdepth 1 -type f -name '*.plugin.zsh' 2>/dev/null | head -1)"
  [[ -n "${plugin_file}" ]] && source "${plugin_file}"
  unset plugin plugin_dir plugin_file
done
unset ZSH_PLUGINS_SKIP

# load ~/.zshrc_base (setup)
[ -r "${HOME}/.zshrc_base" ] && source "${HOME}/.zshrc_base"

# load atuin
[ -x "${HOME}/.atuin/bin/env" ] && source "${HOME}/.atuin/bin/env" &>/dev/null
eval "$(atuin init --disable-up-arrow zsh)"

# load starship
export STARSHIP_CONFIG="${XDG_CONFIG_HOME}/starship/starship.toml"
eval "$(starship init zsh)"

# load direnv hook
(type direnv &>/dev/null) && eval "$(direnv hook zsh)"

# list tmux sessions if not in tmux
if [ -z "${TMUX}" ]; then
  tmux ls 2>/dev/null | while read session; do _info "tmux session:${NC} ${session}"; done
  echo
fi

# get zsh load time - END
_zsh_end="$(date +%s%3N)"
printf " %.3f s\\n" "$((${_zsh_end} - ${_zsh_start}))e-3"
unset _zsh_start _zsh_end

# unload zsh profiler
# zprof 2>&1 >~/.zsh.profiling
# zmodload -u zsh/zprof

######################################################################
# -- DO NOT EDIT THIS FILE --
# Add your customizations in ~/.zshrc_custom and they will
# be loaded automatically when you start a new shell session.
######################################################################
