# Documentation: https://yazi-rs.github.io/docs/configuration/yazi

[mgr]
ratio = [1, 3, 4]
sort_by = "alphabetical"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
sort_translit = false
linemode = "size"
show_hidden = true
show_symlink = true

[preview]
wrap = "no"
tab_size = 2
max_width = 900
max_height = 900
cache_dir = ""
image_delay = 30
image_filter = "triangle"
image_quality = 75
