-- https://github.com/MeanderingProgrammer/render-markdown.nvim
-- Plugin to improve viewing Markdown files in Neovim
return {
  "MeanderingProgrammer/render-markdown.nvim",
  enabled = true,
  dependencies = {
    "nvim-treesitter/nvim-treesitter",
    "nvim-tree/nvim-web-devicons",
  },
  ---@module 'render-markdown'
  ---@type render.md.UserConfig
  opts = {
    heading = {
      enabled = true,
      preset = "obsidian",
      sign = true,
      position = "overlay",
      icons = { "󰲡 ", "󰲣 ", "󰲥 ", "󰲧 ", "󰲩 ", "󰲫 " },
      signs = { "󰫎 " },
      width = "full",
      left_margin = 0,
      right_pad = 0,
      min_width = 0,
      border = false,
      border_virtual = false,
      border_prefix = false,
      above = "▄",
      below = "▀",
      backgrounds = {
        "RenderMarkdownH1Bg",
        "RenderMarkdownH2Bg",
        "RenderMarkdownH3Bg",
        "RenderMarkdownH4Bg",
        "RenderMarkdownH5Bg",
        "RenderMarkdownH6Bg",
      },
      foregrounds = {
        "RenderMarkdownH1",
        "RenderMarkdownH2",
        "RenderMarkdownH3",
        "RenderMarkdownH4",
        "RenderMarkdownH5",
        "RenderMarkdownH6",
      },
    },
    bullet = {
      enabled = true,
      highlight = "RenderMarkdownBullet",
      left_pad = 0,
      render_modes = false,
    },
    callout = {
      abstract = { raw = "[!ABSTRACT]", rendered = "󰨸 Abstract", highlight = "RenderMarkdownInfo" },
      attention = { raw = "[!ATTENTION]", rendered = "󰀪 Attention", highlight = "RenderMarkdownWarn" },
      bug = { raw = "[!BUG]", rendered = "󰨰 Bug", highlight = "RenderMarkdownError" },
      caution = { raw = "[!CAUTION]", rendered = "󰳦 Caution", highlight = "RenderMarkdownError" },
      check = { raw = "[!CHECK]", rendered = "󰄬 Check", highlight = "RenderMarkdownSuccess" },
      cite = { raw = "[!CITE]", rendered = "󱆨 Cite", highlight = "RenderMarkdownQuote" },
      danger = { raw = "[!DANGER]", rendered = "󱐌 Danger", highlight = "RenderMarkdownError" },
      done = { raw = "[!DONE]", rendered = "󰄬 Done", highlight = "RenderMarkdownSuccess" },
      error = { raw = "[!ERROR]", rendered = "󱐌 Error", highlight = "RenderMarkdownError" },
      example = { raw = "[!EXAMPLE]", rendered = "󰉹 Example", highlight = "RenderMarkdownHint" },
      fail = { raw = "[!FAIL]", rendered = "󰅖 Fail", highlight = "RenderMarkdownError" },
      failure = { raw = "[!FAILURE]", rendered = "󰅖 Failure", highlight = "RenderMarkdownError" },
      faq = { raw = "[!FAQ]", rendered = "󰘥 Faq", highlight = "RenderMarkdownWarn" },
      help = { raw = "[!HELP]", rendered = "󰘥 Help", highlight = "RenderMarkdownWarn" },
      hint = { raw = "[!HINT]", rendered = "󰌶 Hint", highlight = "RenderMarkdownSuccess" },
      important = { raw = "[!IMPORTANT]", rendered = "󰅾 Important", highlight = "RenderMarkdownHint" },
      info = { raw = "[!INFO]", rendered = "󰋽 Info", highlight = "RenderMarkdownInfo" },
      missing = { raw = "[!MISSING]", rendered = "󰅖 Missing", highlight = "RenderMarkdownError" },
      note = { raw = "[!NOTE]", rendered = "󰋽 Note", highlight = "RenderMarkdownInfo" },
      question = { raw = "[!QUESTION]", rendered = "󰘥 Question", highlight = "RenderMarkdownWarn" },
      quote = { raw = "[!QUOTE]", rendered = "󱆨 Quote", highlight = "RenderMarkdownQuote" },
      success = { raw = "[!SUCCESS]", rendered = "󰄬 Success", highlight = "RenderMarkdownSuccess" },
      summary = { raw = "[!SUMMARY]", rendered = "󰨸 Summary", highlight = "RenderMarkdownInfo" },
      tip = { raw = "[!TIP]", rendered = "󰌶 Tip", highlight = "RenderMarkdownSuccess" },
      tldr = { raw = "[!TLDR]", rendered = "󰨸 Tldr", highlight = "RenderMarkdownInfo" },
      todo = { raw = "[!TODO]", rendered = "󰗡 Todo", highlight = "RenderMarkdownInfo" },
      warning = { raw = "[!WARNING]", rendered = "󰀪 Warning", highlight = "RenderMarkdownWarn" },
    },
    checkbox = {
      -- enabled = true,
      left_pad = 0,
      position = "inline",
      checked = { scope_highlight = "@markup.strikethrough" },
      custom = {
        todo = { raw = "[-]", rendered = " ", highlight = "RenderMarkdownTodo", scope_highlight = nil },
        wip = { raw = "[/]", rendered = " ", highlight = "RenderMarkdownTodo", scope_highlight = nil },
        -- obsidian
        bookmark = { raw = "[b]", rendered = " ", highlight = "RenderMarkdownTodo", scope_highlight = nil },
        important = { raw = "[!]", rendered = " ", highlight = "DiagnosticWarn" },
        info = { raw = "[i]", rendered = "󰋼 ", highlight = "RenderMarkdownInfo", scope_highlight = nil },
        pr_draft = { raw = "[D]", rendered = " ", highlight = "DiagnosticWarn", scope_highlight = nil },
        pr_merged = { raw = "[M]", rendered = " ", highlight = "RenderMarkdownSuccess", scope_highlight = nil },
        pr_open = { raw = "[P]", rendered = " ", highlight = "RenderMarkdownTodo", scope_highlight = nil },
        question = { raw = "[?]", rendered = " ", highlight = "DiagnosticWarn", scope_highlight = nil },
      },
      link = {
        custom = {
          go = { pattern = "%.go$", icon = " " },
          jinja = { pattern = "%.j2$", icon = " " },
          markdown = { pattern = "%.md$", icon = " " },
          perl = { pattern = "%.pl$", icon = " " },
          python = { pattern = "%.py$", icon = "󰌠 " },
          ruby = { pattern = "%.rb$", icon = " " },
          shell = { pattern = "%.sh$", icon = " " },
          yaml = { pattern = "%.yaml$", icon = " " },
          yml = { pattern = "%.yml$", icon = " " },
        },
      },
    },
    code = {
      border = "thin",
      language_pad = 2,
      left_pad = 2,
      min_width = 45,
      sign = "language",
      width = "block",
    },
    dash = {
      enabled = true,
      highlight = "RenderMarkdownDash",
      icon = "─",
      render_modes = false,
      width = "full",
    },
  },
}
